# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftEx-1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftEx-1
  pod 'SnapKit', '~> 5.6.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'RxSwiftEx-1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftEx-1UITests' do
    # Pods for testing
  end

end
